[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "node"
command_arguments = ["node_modules/tailwindcss/lib/cli", "-i", "index.css",  "-o",  "dist/.stage/index.css"]

[profile.release]
# Do not perform backtrace for panic on release builds.
panic = 'abort'
# Perform optimizations on all codegen units.
codegen-units = 1
# Optimize for size.
opt-level = 's' # or 'z' to optimize "aggressively" for size
# Enable link time optimization.
lto = true
