[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "node"
command_arguments = ["node_modules/tailwindcss/lib/cli", "-i", "styles.css",  "-o",  "index.css", "--minify"]
