# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build status

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tailwind deps
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Install Rust toolchain and build
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked trunk
          trunk build --release
      - name: Deploy dist to gh-pages
        if: True
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
